name: Update pinned release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update pinned release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v0.0.1
          name: Stable release
          body: |
            Automatic update of PowerShell setup scripts.
            Latest commit: ${{ github.sha }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
          files: |
            WinSetup.bat
            *.ps1
